name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # or change to 'master' if you're using that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (required by Pages)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ https://github.com/amritbir-singh/example.git
